{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "BeautifulSoup",
      "provenance": [],
      "authorship_tag": "ABX9TyP2hmja+3jG0NVSW9kRvpfl"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "QA8iKfOfU_3-",
        "outputId": "31c0c3dc-6898-4412-c8da-ec940a9f7d53"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Enter - https://pypi.python.org/pypi/beautifulsoup4\n",
            "#content\n",
            "/\n",
            "/help/\n",
            "/sponsors/\n",
            "/account/login/\n",
            "/account/register/\n",
            "/help/\n",
            "/sponsors/\n",
            "/account/login/\n",
            "/account/register/\n",
            "/project/beautifulsoup4/\n",
            "#description\n",
            "#history\n",
            "#files\n",
            "http://www.crummy.com/software/BeautifulSoup/bs4/\n",
            "http://www.crummy.com/software/BeautifulSoup/bs4/download/\n",
            "https://libraries.io/pypi/beautifulsoup4\n",
            "https://packaging.python.org/guides/analyzing-pypi-package-downloads/\n",
            "mailto:leonardr@segfault.org\n",
            "/user/leonard/\n",
            "/search/?c=Development+Status+%3A%3A+5+-+Production%2FStable\n",
            "/search/?c=Intended+Audience+%3A%3A+Developers\n",
            "/search/?c=License+%3A%3A+OSI+Approved+%3A%3A+MIT+License\n",
            "/search/?c=Programming+Language+%3A%3A+Python\n",
            "/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3\n",
            "/search/?c=Topic+%3A%3A+Software+Development+%3A%3A+Libraries+%3A%3A+Python+Modules\n",
            "/search/?c=Topic+%3A%3A+Text+Processing+%3A%3A+Markup+%3A%3A+HTML\n",
            "/search/?c=Topic+%3A%3A+Text+Processing+%3A%3A+Markup+%3A%3A+SGML\n",
            "/search/?c=Topic+%3A%3A+Text+Processing+%3A%3A+Markup+%3A%3A+XML\n",
            "#description\n",
            "#data\n",
            "#history\n",
            "#files\n",
            "http://www.crummy.com/software/BeautifulSoup/bs4/doc/\n",
            "http://www.crummy.com/software/BeautifulSoup/bs4/\n",
            "http://www.crummy.com/software/BeautifulSoup/bs4/doc/\n",
            "http://groups.google.com/group/beautifulsoup/\n",
            "https://code.launchpad.net/beautifulsoup/\n",
            "https://bugs.launchpad.net/beautifulsoup/\n",
            "https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/CHANGELOG\n",
            "https://tidelift.com/subscription/pkg/pypi-beautifulsoup4?utm_source=pypi-beautifulsoup4&utm_medium=referral&utm_campaign=readme\n",
            "https://www.crummy.com/software/BeautifulSoup/zine/\n",
            "http://www.crummy.com/software/BeautifulSoup/bs4/\n",
            "http://www.crummy.com/software/BeautifulSoup/bs4/download/\n",
            "https://libraries.io/pypi/beautifulsoup4\n",
            "https://packaging.python.org/guides/analyzing-pypi-package-downloads/\n",
            "mailto:leonardr@segfault.org\n",
            "/user/leonard/\n",
            "/search/?c=Development+Status+%3A%3A+5+-+Production%2FStable\n",
            "/search/?c=Intended+Audience+%3A%3A+Developers\n",
            "/search/?c=License+%3A%3A+OSI+Approved+%3A%3A+MIT+License\n",
            "/search/?c=Programming+Language+%3A%3A+Python\n",
            "/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3\n",
            "/search/?c=Topic+%3A%3A+Software+Development+%3A%3A+Libraries+%3A%3A+Python+Modules\n",
            "/search/?c=Topic+%3A%3A+Text+Processing+%3A%3A+Markup+%3A%3A+HTML\n",
            "/search/?c=Topic+%3A%3A+Text+Processing+%3A%3A+Markup+%3A%3A+SGML\n",
            "/search/?c=Topic+%3A%3A+Text+Processing+%3A%3A+Markup+%3A%3A+XML\n",
            "/help/#project-release-notifications\n",
            "/rss/project/beautifulsoup4/releases.xml\n",
            "/project/beautifulsoup4/4.10.0/\n",
            "/project/beautifulsoup4/4.9.3/\n",
            "/project/beautifulsoup4/4.9.2/\n",
            "/project/beautifulsoup4/4.9.1/\n",
            "/project/beautifulsoup4/4.9.0/\n",
            "/project/beautifulsoup4/4.8.2/\n",
            "/project/beautifulsoup4/4.8.1/\n",
            "/project/beautifulsoup4/4.8.0/\n",
            "/project/beautifulsoup4/4.7.1/\n",
            "/project/beautifulsoup4/4.7.0/\n",
            "/project/beautifulsoup4/4.6.3/\n",
            "/project/beautifulsoup4/4.6.2/\n",
            "/project/beautifulsoup4/4.6.1/\n",
            "/project/beautifulsoup4/4.6.0/\n",
            "/project/beautifulsoup4/4.5.3/\n",
            "/project/beautifulsoup4/4.5.2/\n",
            "/project/beautifulsoup4/4.5.1/\n",
            "/project/beautifulsoup4/4.5.0/\n",
            "/project/beautifulsoup4/4.4.1/\n",
            "/project/beautifulsoup4/4.4.0/\n",
            "/project/beautifulsoup4/4.3.2/\n",
            "/project/beautifulsoup4/4.3.1/\n",
            "/project/beautifulsoup4/4.3.0/\n",
            "/project/beautifulsoup4/4.2.1/\n",
            "/project/beautifulsoup4/4.2.0/\n",
            "/project/beautifulsoup4/4.1.3/\n",
            "/project/beautifulsoup4/4.1.2/\n",
            "/project/beautifulsoup4/4.1.1/\n",
            "/project/beautifulsoup4/4.1.0/\n",
            "/project/beautifulsoup4/4.0.5/\n",
            "/project/beautifulsoup4/4.0.4/\n",
            "/project/beautifulsoup4/4.0.3/\n",
            "/project/beautifulsoup4/4.0.2/\n",
            "/project/beautifulsoup4/4.0.1/\n",
            "https://packaging.python.org/installing/\n",
            "https://files.pythonhosted.org/packages/a1/69/daeee6d8f22c997e522cdbeb59641c4d31ab120aba0f2c799500f7456b7e/beautifulsoup4-4.10.0.tar.gz\n",
            "#copy-hash-modal-9aeb3228-d8c3-419a-8dac-92d52ebd165d\n",
            "https://files.pythonhosted.org/packages/69/bf/f0f194d3379d3f3347478bd267f754fc68c11cbf2fe302a6ab69447b1417/beautifulsoup4-4.10.0-py3-none-any.whl\n",
            "#copy-hash-modal-55837847-0d78-4440-b8fa-7d2eaa6b25df\n",
            "#modal-close\n",
            "https://pip.pypa.io/en/stable/cli/pip_install/#hash-checking-mode\n",
            "#modal-close\n",
            "#modal-close\n",
            "https://pip.pypa.io/en/stable/cli/pip_install/#hash-checking-mode\n",
            "#modal-close\n",
            "https://packaging.python.org/installing/\n",
            "https://packaging.python.org/tutorials/packaging-projects/\n",
            "https://packaging.python.org/\n",
            "/help/\n",
            "https://twitter.com/PyPI\n",
            "https://dtdg.co/pypi\n",
            "https://www.python.org/dev/peps/pep-0541/\n",
            "/sponsors/\n",
            "/help/#feedback\n",
            "https://github.com/pypa/warehouse\n",
            "https://hosted.weblate.org/projects/pypa/warehouse/\n",
            "https://github.com/pypa/warehouse/graphs/contributors\n",
            "https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md\n",
            "/security/\n",
            "https://www.python.org/privacy/\n",
            "/policy/terms-of-use/\n",
            "https://status.python.org/\n",
            "https://donate.pypi.org\n",
            "https://www.python.org/psf/\n",
            "/sitemap/\n",
            "https://aws.amazon.com/\n",
            "https://www.datadoghq.com/\n",
            "https://research.fb.com/\n",
            "https://www.fastly.com/\n",
            "https://careers.google.com/\n",
            "https://www.python.org/psf/sponsors/#huawei\n",
            "https://www.python.org/psf/sponsors/#microsoft\n",
            "https://www.python.org/psf/sponsors/#nvidia\n",
            "https://www.pingdom.com/\n",
            "https://opensource.salesforce.com/\n",
            "https://getsentry.com/for/python\n",
            "https://statuspage.io\n"
          ]
        }
      ],
      "source": [
        "# To run this, you can install BeautifulSoup\n",
        "# https://pypi.python.org/pypi/beautifulsoup4\n",
        "\n",
        "# Or download the file\n",
        "# http://www.py4e.com/code3/bs4.zip\n",
        "# and unzip it in the same directory as this file\n",
        "\n",
        "import urllib.request, urllib.parse, urllib.error\n",
        "from bs4 import BeautifulSoup\n",
        "import ssl\n",
        "\n",
        "# Ignore SSL certificate errors\n",
        "ctx = ssl.create_default_context()\n",
        "ctx.check_hostname = False\n",
        "ctx.verify_mode = ssl.CERT_NONE\n",
        "\n",
        "url = input('Enter - ')\n",
        "html = urllib.request.urlopen(url, context=ctx).read()\n",
        "soup = BeautifulSoup(html, 'html.parser')\n",
        "\n",
        "# Retrieve all of the anchor tags\n",
        "tags = soup('a')\n",
        "for tag in tags:\n",
        "    print(tag.get('href', None))"
      ]
    }
  ]
}